docker-compose-yaml: docker-compose.yml

project: uu-pentest

tasks:
  post-rollout:
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  one:
    cronjobs:
      - name: drush cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
  two:
    cronjobs:
      - name: drush cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
